### PR TITLE
Merged base KMotionX swig changes, added local changes

### PR DESCRIPTION
**Pull request by meantaipan**
Hi Par,
I merged your changes to the swig branch, and added quite a bit of stuff which I had locally, including some command-line args for the kmotion server to select whether to support TCP sockets.

### CODE REVIEW

**Comment by parhansson** [comment]
Great. I have been looking forward to the new 4.33 release. Once I get this working and cleaned up I'm planning to merge this into the master branch. 
I was just about to dig into the 4.33 changes. Thank you for doing this so easy for me. :)

**Comment by meantaipan** [comment]
Hi Pär,

No problem.  There might be a few minor changes for 4.33 release.  I merged
in most stuff up to then.  Note that I keep the 'master' branch up-to-date
with the Dynomotion releases, then merge into 'swig', so I am basically
maintaining two points in the repo.  It's useful to be able to see what
Dynomotion changes.

I just pushed up that master branch to github.

It seems that we may be developing some software along similar lines.  I'd
be interested in getting some more info from you on what you are doing with
http servers and the like.  On my side, I have been doing a lot of
development on my Python/GTK+3 CNC application, which is going pretty
nicely.  I thought that using HTML5 would be a good way to add
functionality to it, so I added Python modules for an HTTP and WebSockets
server.  WS is very interesting technology: unfortunately it is fairly new
so not supported on mobile devices yet, but modern desktop browsers support
it.  For 3D I am using WebGL, and using scenejs to do the scene
management.

Regards,
SJH

**Comment by parhansson** [comment]
Hi SJH

Keeping the master branch clean is a very good idea I will do the same. I have synced my master branch with the latest release (4.33).  Maybe some changes in the master could be done to not be as intrusive to the original code. You are using some virtual methods in the Swig branch. Maybe that can be a solution to this. Maybe it would be possible to get some of the changes into the original code base to ease up future updates. 

I'm using a HTTP server with a small footprint written in C called mongoose. To that i have written a backend (handler.cpp) that listens to WebSockets and http requests. The backend/handler keeps the GCodeInterpreter and KMotionDLL instances and use WebSockets to push status updates and syncs other data between clients. Hence the state is in the backend and the web clients acts on these updates. If one browser is connected on the computer and one on my phone at the same time. It would be unfortunate if the GUI's and GCodeInterpreter states are not synced between the two. So when I open a gcode file on one device the other instantly opens the same file. If a message to the user from the controller is issued and no browser is listening (due to network failure or answering the phone or accidentally closing the browser) the message is queued and resent until at least one client has acknowledged or answered the message depending on type.

I think WebSockets are supported well enough to be used. It works well in Safari on Iphone and iPad. Haven't testet on android but according to this it should work with Chrome on Android. http://caniuse.com/#search=websocket

The communication can be quite intense so to avoid hanging GUI I use a web worker to handle communication in the background. 

I use Three.js to render the WebGL parts. I wasn't aware of scenejs until now. But that actually seems to be a better choice for this kind of work. Maybe I'll switch to that.

The GUI has support(syntax highlighting) for editing both C-files for KFlop programs and GCode.
Importing files can be done by dragging a file into to GCode editor and will be transformed to runnable GCode. Supported formats are simple text GCode(no transforming), SVG and Adode Illustrator files that actually is a subset of PDF do that works as well. Currently only vectors from SVG and PDFs are transformed to GCode.

I'm working on transforming the glyphs to get GCode for plain text. Mostly useful when using laser cutters of course. But that is what I'm currently using my KFlop on. My mill is not up an running at the moment. (For a while now to be honest). 

Working in javascript and building GUI with Angular is so much faster than C or C++. Debug and make code updates in browser while running. I Like that. Also when running the backend on a Raspberry or Beagle the front end can do the heavy lifting of rendering stuff. 

Although with a growing application I'm considering adopting TypeScript. I have recently added a concept of what i call Intermediate GCode model (IGM). The IGM will allow for some kind of CAM features. I try to write the code so it will be easy to add plugins that can modify the IGM. This concept is what use when I import files going from PDF to SVG to IGM to Gcode. This is in an early stage though so changes in GCode does not affect the IGM just yet.

Have you tried the KMotionXCNC app?

Regards
Pär

**Comment by meantaipan** [comment]
On Sun, Dec 13, 2015 at 1:06 PM, Pär Hansson notifications@github.com
wrote:

> Hi SJH
> 
> Keeping the master branch clean is a very good idea I will do the same. I
> have synced my master branch with the latest release (4.33). Maybe some
> changes in the master could be done to not be as intrusive to the original
> code. You are using some virtual methods in the Swig branch. Maybe that can
> be a solution to this. Maybe it would be possible to get some of the
> changes into the original code base to ease up future updates.
> 
> If I was to do it over, it would be less intrusive on Tom's code base,
> however I find it is not too difficult to merge in new releases.  There are
> not too many conflicts, since most new development on my side has been on
> the files unique to the swig branch.

That might change when I get around to modifying the g-code interpreter to
support tool orientation modes - we will eventually want true 5-axis
support for our machine.  We already have the kinematics working for our
trunnion table, but g-code support is still limited to inverse time feed
mode.

> I'm using a HTTP server with a small footprint written in C called
> mongoose. To that i have written a backend (handler.cpp) that listens to
> WebSockets and http requests. The backend/handler keeps the
> GCodeInterpreter and KMotionDLL instances and use WebSockets to push status
> updates and syncs other data between clients. Hence the state is in the
> backend and the web clients acts on these updates. If one browser is
> connected on the computer and one on my phone at the same time. It would be
> unfortunate if the GUI's and GCodeInterpreter states are not synced between
> the two. So when I open a gcode file on one device the other instantly
> opens the same file. If a message to the user from the controller is issued
> and no browser is listening (due to network failure or answering the phone
> or accidentally closing the browser) the message is queued and resent until
> at least one client has acknowledged or answered the message depending on
> type.
> 
> That makes sense.  I'll take a look at Mongoose.
> 
> I think WebSockets are supported well enough to be used. It works well in
> Safari on Iphone and iPad. Haven't testet on android but according to this
> it should work with Chrome on Android.
> http://caniuse.com/#search=websocket
> 
> I have a Nexus 7, but it wouldn't connect via WS.  It probably needs an
> upgrade, although I have the latest version for that device.  Not that
> worried; I don't think we have any particular need for mobile support, but
> it would be nice to have.
> 
> The communication can be quite intense so to avoid hanging GUI I use a web
> worker to handle communication in the background.
> 
> If you look at what I did in swig_extras.cpp, it has an 'event dispatcher'
> which might help cut down on unnecessary traffic.  Basically, when polling
> the kflop it looks for differences in the state, and will only generate an
> event if the data changes.

To use this, subclass the GCodeInterpreter class and add virtual function
implementations for HandleBoolEvent(), HandleIntEvent() etc.  When starting
up, call EnableEvent() for each event code of interest (codes listed in
swig_extras_events.cpp.  e.g. specify CHG_POS+2 as the event id to get
notified of changes in the Z axis position).  Then, whenever you call
Poll(), the appropriate event handler will be invoked whenever the data
changes.

I haven't yet looked into web workers.  At present, my client side mostly
accepts messages pushed from the server side and updates the display.
Messages are currently JSON encoded, so that is a bit of overhead, but I am
not familiar enough with javascript to do much better.  Anyway, the server
pushes a machine model in the json format expected by scenejs.  Just simple
geometry at present, although scenejs handles various 3D geometry formats
so we'll eventually try it out on a more realistic model.

I have just got toolpath display working, where the server pushes out
line-strip geometry which is then added to the model.

> I use Three.js to render the WebGL parts. I wasn't aware of scenejs until
> now. But that actually seems to be a better choice for this kind of work.
> Maybe I'll switch to that.
> 
> I recommend getting the latest snapshot from github.  I had to make a fix
> to it to get hierarchical model transforms propagating correctly, but as
> yet it is not in the main repo, so you can get it from meantaipan if you
> want that fix.  Of course I don't know what I'm doing regarding js, but it
> works for me :-)
> 
> The GUI has support(syntax highlighting) for editing both C-files for
> KFlop programs and GCode.
> Importing files can be done by dragging a file into to GCode editor and
> will be transformed to runnable GCode. Supported formats are simple text
> GCode(no transforming), SVG and Adode Illustrator files that actually is a
> subset of PDF do that works as well. Currently only vectors from SVG and
> PDFs are transformed to GCode.
> 
> I'm working on transforming the glyphs to get GCode for plain text. Mostly
> useful when using laser cutters of course. But that is what I'm currently
> using my KFlop on. My mill is not up an running at the moment. (For a while
> now to be honest).
> 
> That sounds really nice.  I do have some code which uses the FreeType
> library to convert vector font files into usable data, but it is further
> work to convert that to g-code.  I think it would be nice to use the Pango
> text layout engine, although I would take your advice on that.  I also have
> some code to convert vector/outline fonts to Voronoi sets, so one could
> generate single-pass toolpaths to engrave the letters using a conical tip
> tool.  But that needs a lot more work.
> 
> Working in javascript and building GUI with Angular is so much faster than
> C or C++. Debug and make code updates in browser while running. I Like
> that. Also when running the backend on a Raspberry or Beagle the front end
> can do the heavy lifting of rendering stuff.
> 
> I'm more of a Python guy, but I do need to look into Angular and other
> application frameworks.
> 
> Although with a growing application I'm considering adopting TypeScript. I
> have recently added a concept of what i call Intermediate GCode model
> (IGM). The IGM will allow for some kind of CAM features. I try to write the
> code so it will be easy to add plugins that can modify the IGM. This
> concept is what use when I import files going from PDF to SVG to IGM to
> Gcode. This is in an early stage though so changes in GCode does not affect
> the IGM just yet.
> 
> Interesting.  I'm working on a Python class right now which encapsulates
> toolpath geometry.  For example, it stores not only geometry but feed rates
> and tool orientation.  Currently it can perform some useful polygon
> operations like offsetting, Voronoi, and boolean combinations.  It can
> import outline fonts.  The initial intent is to make it easy to do simple
> cad operations when a full-blown cad (like Solidworks) is not desired.

Unfortunately, it's not javascript - in fact, uses boost c++ libraries - so
cannot be run client-side.  Maybe a protocol could be devised so that the
server does the main work.

> Have you tried the KMotionXCNC app?
> 
> Not yet, but I would like to.  What port number does it listen on?  Any
> how-to documentation yet?

Regards,
SJH

**Comment by meantaipan** [comment]
Trying to run kmxWeb: it gets a SEGV when trying to open the settings file,
which it expects to be under the bin directory, but the build process
doesn't seem to put it there.  Actually, the SEGV is when it is trying to
close the file pointer, which is null.

So I copied over the settings files, but when I browse to port 8080, it
just indexes the bin directory.  I'm obviously missing something - command
line args?

I did take a look at the app just by clicking on index.html - looks very
nice.

I had a look through the server code.  (Have a long way to go before I
understand the client)  You are sending the kflop status packet in binary
over WebSockets, no?  I didn't try binary messages because I didn't know
how to handle them in javascript.  I know it has typed arrays, but that's
about the limit of it for me.  I was thinking that we should design a
protocol to _abstract_ out the kflop-specifics; have that done by the
server, which then pushes higher level messages to the client, somewhat
based on the event model in swig_extras that I mentioned previously.  That
way, the client would have some control over the messages which were sent,
and it could react to just those messages which were desired.  Since
javascript is fairly slow, this might improve app performance (not that I
have tried it and found it wanting, but reduced overhead is always good).

Currently I have a json-based protocol: websocket is used to send and
receive objects like {"type":"foo", "foo":{ data for foo }}.  json is
fairly verbose compared with binary, but it does have the great advantage
of extensibility and platform independence (no struggles with endianness
and packing!).  With a bit of design, it can be reasonably efficient,
javascript obviously likes it, and it is easy to parse/generate in C.

Maybe if we designed a json protocol, then it would be a useful basis for
custom applications.  Initially, I could write a Python server
implementation which would be useful for experimentation and validation
that the protocol does what is required.  Tell me if you think this would
be useful; I could spend a week or so to get something working.  Basically,
it would be pulling some existing code out of my simplecnc application.

Regards,
SJH

**Comment by parhansson** [comment]
You need to set document root on startup. (This is something I have meant to fix. But just didn't do.)
./kmxWeb -document_root ../KMotionX/KMotionXCNC/app
Then preferably use Chrome to browse http://localhost:8080

I use a json-based protocol too that is about the same as yours. Although each message also has an id that must be acknowledged by at least one client or it will be resent after a while. This is to ensure the blocking messages that pauses jobs is actually handled by a client application or the backend will block forever. In the Debug tab (Raw communication panel) in the client app you can see the messages. 
Only the global status updates from KFlop is using the binary protocol(Does not show in debug tab).

Currently there are five message types defined in handler.cpp (CB is for callback) using the json protocol.

``` C
enum cb_type {
  CB_STATUS, //Non blocking callback. Called from the interpreter in different thread
  CB_COMPLETE, //Non blocking callback. Called from the interpreter in different thread
  CB_ERR_MSG,      //Non blocking callback
  CB_CONSOLE,      //Non blocking callback, event though it has return value??
  CB_USER, //Blocking callback. Called from the interpreter in different thread
  CB_USER_M_CODE, //Blocking callback. Called from the interpreter in different thread
  CB_STATE, // contains loaded machine configuration(trajectory planning etc) and loaded gcode file
  CB_MESSAGEBOX //Message box and AfxMessageBox
};
```

Examples: 
CB_STATUS

``` javascript
{ "id": 2204, "type": "STATUS", "block": false, "data": { "line": 544, "message": " 547 -
STRAIGHT_FEED(41.6810, 8.3160, 6.0000, 0.0000)@1450085581.161\r\n" }}
```

CB_STATE

``` javascript
 { "id": 2214, "type": "STATE", "block": false, "data": {"file": "gcode/examples/octocat.gcode", "machine": "settings/laser.cnf" }}
```

Every message is acknowledged with a response that should be JSON formatted but isn't because when I wrote that I didn't use a JSON parser and did put in the effort to parse it.
It consists of ID type and return value. 

``` C
"CB_ACK: 2214 STATE -1"
```

That is whats going on over the WebSocket. 

For all other calls initiated by user such as "Cycle Start" and "Feed Hold" i use a rest based API where parameters are sent in an array instead of naming them individually to avoid some backend parsing. I was a bit lazy when I implemented that. JSON is self documenting if a good naming policy is followed. So it would probably be a good idea to use specific objects for each call. The current implemented commands using the rest protocol can be seen in file.
KMotionX/KMotionXCNC/app/js/backend/kmxBackend.service.js
I have a legacy(that will be removed) of always adding a return parameter even for void methods.

``` javascript
 {"ret":null}
```

I guess it is about time for me to document and clean up some code. The backend callback code over the WebSocket is not easy to follow.  

I realize now that the code base for the web server has taken some giant leaps forward since the version I use. 

I have been thinking of using NodeJs instead as backend server and using SWIG to generate KMotion bindings to the V8 engine, allowing to use javascript on the backend as well. Then both client and backend could share the same code. Since the javascript engines use JIT-compilers there is not as much performance penalty as one might think. 
http://asmjs.org. Is a project where any source code that can be compiled with llvm compiler can be transpiled into a very efficient subset of javascript with performance comparable to Java or .Net. (currently only FireFox engine has performance benefits from this) 

About the Python server. I'm not very familiar with Python. Hence I don't know if I will be using it to the extent it was intended for since I won't be able to easily add features. But I know Python is widely used and lots of good libraries are available with python bindings so adding backend features would be easy. 
If you do it i will definitely give it a try.

**Pull request merged**
